spring.application.name=urlShortnerBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/urlShortnerDB
spring.datasource.username=postgres
spring.datasource.password=Mishraji04$()
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret = 567f7075fa9f71656d11d2b21d3b79307737d2027ba3006858623f0a801ceb2d
jwt.expiration = 172800000